version: "2"
volumes:
    mysql-db: {}
services:
    db-mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: attableDB
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: admin1234
        volumes:
            - mysql-db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        ports:
            - 3306:3306/tcp
