version: "3.2"
services:
    app:
        restart: always
        # image: artisandigitalasia/attable-backend:staging
        build: .
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
            - "SPRING_DATASOURCE_URL=jdbc:mysql://turntable.proxy.rlwy.net:24510/attableDB?createDatabaseIfNotExist=true&serverTimezone=Asia/Bangkok&useLegacyDatetimeCode=false"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=BpEcPxuEZRzWmVqXTnbnfpOLlpzrrSzA"
            - "JWT_SECRET=JWTSuperSecretKey"
            - "OMISE_KEY=skey_test_5gwxqp61kiy214mn2la"
            - "MAIL_USERNAME=sapolayot.nantawong@gmail.com"
            - "MAIL_PASSWORD=Lampang005001234"
        ports:
            - 8080:8080
